<?php
/**
 * Dear Theme — Article Footer Render Helper
 *
 * Provides static methods to render the article footer components:
 * metadata area, custom badges, and copyright notices.
 */
if (!defined('__TYPECHO_ROOT_DIR__'))
    exit;

class DearTheme_ArticleFooter
{
    /**
     * Get the default badge groups JSON
     */
    public static function defaultBadgeGroups()
    {
        return json_encode([
            [
                'id' => 'ai_writing',
                'name' => 'AI 写作',
                'mode' => 'single',
                'badges' => [
                    [
                        'id' => 'ai_none',
                        'label' => 'AI',
                        'value' => 'NOT BY AI',
                        'color' => '#2e6f40',
                        'tooltip' => '纯人类创作，未使用人工智能生成文本。',
                        'link' => ''
                    ],
                    [
                        'id' => 'ai_assisted',
                        'label' => 'AI',
                        'value' => 'ASSISTED BY AI',
                        'color' => '#2b5d8c',
                        'tooltip' => '仅使用AI协作查找资料或润色，正文由人类撰写。',
                        'link' => ''
                    ],
                    [
                        'id' => 'ai_cowritten',
                        'label' => 'AI',
                        'value' => 'CO-WRITTEN WITH AI',
                        'color' => '#b35900',
                        'tooltip' => '本文部分核心段落借助AI进行生成与重写。',
                        'link' => ''
                    ],
                    [
                        'id' => 'ai_generated',
                        'label' => 'AI',
                        'value' => 'GENERATED BY AI',
                        'color' => '#8c2b2b',
                        'tooltip' => '本文内容完全由人工智能模型生成。',
                        'link' => ''
                    ]
                ]
            ],
            [
                'id' => 'reading',
                'name' => '阅读',
                'mode' => 'multi',
                'badges' => [
                    [
                        'id' => 'long_read',
                        'label' => 'CONTENT',
                        'value' => 'LONG ARTICLE',
                        'color' => '#555555',
                        'tooltip' => '长篇文章，预计阅读时间 >15 分钟。',
                        'link' => ''
                    ],
                    [
                        'id' => 'short_read',
                        'label' => 'CONTENT',
                        'value' => 'SHORT ARTICLE',
                        'color' => '#2e6f40',
                        'tooltip' => '短篇文章，预计阅读时间 <5 分钟。',
                        'link' => ''
                    ],
                    [
                        'id' => 'word_count_high',
                        'label' => 'CONTENT',
                        'value' => '10000+ WORDS',
                        'color' => '#555555',
                        'tooltip' => '本文字数超过一万字。',
                        'link' => ''
                    ]
                ]
            ],
            [
                'id' => 'media_info',
                'name' => '媒体信息',
                'mode' => 'multi',
                'badges' => [
                    [
                        'id' => 'webp',
                        'label' => 'MEDIA',
                        'value' => 'WEBP',
                        'color' => '#632b8c',
                        'tooltip' => '图像采用WEBP格式压缩，画质较原图有所下降。',
                        'link' => ''
                    ],
                    [
                        'id' => 'has_video',
                        'label' => 'MEDIA',
                        'value' => 'VIDEO',
                        'color' => '#2b5d8c',
                        'tooltip' => '本文包含视频内容。',
                        'link' => ''
                    ],
                    [
                        'id' => 'has_audio',
                        'label' => 'MEDIA',
                        'value' => 'AUDIO',
                        'color' => '#2b5d8c',
                        'tooltip' => '本文包含音频内容。',
                        'link' => ''
                    ]
                ]
            ]
        ], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
    }

    /**
     * Get the default copyright presets JSON
     */
    public static function defaultCopyrightPresets()
    {
        return json_encode([
            'contentGroups' => [
                [
                    'id' => 'cc',
                    'name' => 'CC 4.0',
                    'description' => '知识共享4.0国际许可协议',
                    'hasMarks' => true,
                    'marks' => [
                        [
                            'id' => 'BY',
                            'text' => 'BY',
                            'tooltip' => '署名：引用或使用本文内容时必须注明明确出处',
                            'required' => false
                        ],
                        [
                            'id' => 'NC',
                            'text' => 'NC',
                            'tooltip' => '非商业性使用：您不能利用本文内容进行商业化行为',
                            'required' => false
                        ],
                        [
                            'id' => 'SA',
                            'text' => 'SA',
                            'tooltip' => '相同方式共享：二次创作必须在发布时使用同样的CC协议',
                            'required' => false
                        ],
                        [
                            'id' => 'ND',
                            'text' => 'ND',
                            'tooltip' => '禁止演绎：您不能对本文内容进行任何形式的修改或二次创作',
                            'required' => false
                        ]
                    ]
                ],
                [
                    'id' => 'cc0',
                    'name' => 'CC0',
                    'description' => '公有领域，放弃所有权利',
                    'hasMarks' => false,
                    'link' => 'https://creativecommons.org/publicdomain/zero/1.0/',
                    'badge' => ['text' => 'CC0 Public Domain', 'tooltip' => '作品已贡献至公有领域，放弃所有版权限制']
                ],
                [
                    'id' => 'all_rights',
                    'name' => 'All Rights Reserved',
                    'description' => '保留所有权利',
                    'hasMarks' => false,
                    'link' => '',
                    'badge' => ['text' => '© All Rights Reserved', 'tooltip' => '保留所有权利。未经许可，禁止任何形式的转载或演绎']
                ]
            ],
            'codePresets' => [
                [
                    'id' => 'mit',
                    'name' => 'MIT License',
                    'description' => 'MIT开源协议',
                    'link' => 'https://opensource.org/licenses/MIT',
                    'badgeLabel' => 'OPEN SOURCED',
                    'badgeValue' => 'MIT LICENSE',
                    'badgeColor' => '#555555'
                ],
                [
                    'id' => 'gpl3',
                    'name' => 'GPL 3.0',
                    'description' => 'GPL 3.0开源协议',
                    'link' => 'https://www.gnu.org/licenses/gpl-3.0.html',
                    'badgeLabel' => 'OPEN SOURCED',
                    'badgeValue' => 'GPL 3.0',
                    'badgeColor' => '#555555'
                ]
            ]
        ], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
    }

    /**
     * Build CC license link from selected mark IDs
     */
    private static function buildCcLink($marks)
    {
        $slugMap = [
            'BY' => 'by',
            'NC' => 'nc',
            'SA' => 'sa',
            'ND' => 'nd'
        ];
        $slugs = [];
        $order = ['BY', 'NC', 'SA', 'ND'];
        foreach ($order as $m) {
            if (in_array($m, $marks) && isset($slugMap[$m])) {
                $slugs[] = $slugMap[$m];
            }
        }
        if (empty($slugs))
            return '';
        return 'https://creativecommons.org/licenses/' . implode('-', $slugs) . '/4.0/';
    }

    /**
     * Escape HTML attribute value
     */
    private static function esc($str)
    {
        return htmlspecialchars($str, ENT_QUOTES, 'UTF-8');
    }

    /**
     * Render a single badge-group element (label + value style)
     */
    public static function renderBadgeElement($badge)
    {
        $tooltip = !empty($badge['tooltip']) ? ' data-tooltip="' . self::esc($badge['tooltip']) . '"' : '';
        $tag = !empty($badge['link']) ? 'a' : 'div';
        $href = !empty($badge['link']) ? ' href="' . self::esc($badge['link']) . '" target="_blank" rel="noopener noreferrer"' : '';
        $color = !empty($badge['color']) ? $badge['color'] : '#555555';

        $html = '<' . $tag . ' class="badge-group"' . $tooltip . $href . '>';
        if (!empty($badge['label'])) {
            $html .= '<span class="badge-label">' . self::esc($badge['label']) . '</span>';
        }
        if (!empty($badge['value'])) {
            $html .= '<span class="badge-value" style="background-color:' . self::esc($color) . ';">' . self::esc($badge['value']) . '</span>';
        }
        $html .= '</' . $tag . '>';

        return $html;
    }

    /**
     * Render the custom badges section
     *
     * @param string $badgeGroupsJson  JSON string of all badge groups from theme settings
     * @param string $selectedIdsJson  JSON string of selected badge IDs for this article
     * @return string HTML output
     */
    public static function renderBadges($badgeGroupsJson, $selectedIdsJson)
    {
        $groups = json_decode($badgeGroupsJson, true);
        $selectedIds = json_decode($selectedIdsJson, true);

        if (empty($groups) || empty($selectedIds) || !is_array($groups) || !is_array($selectedIds)) {
            return '';
        }

        $badges = [];
        foreach ($groups as $group) {
            if (empty($group['badges']) || !is_array($group['badges']))
                continue;
            foreach ($group['badges'] as $badge) {
                if (in_array($badge['id'], $selectedIds)) {
                    $badges[] = $badge;
                }
            }
        }

        if (empty($badges)) {
            return '';
        }

        $html = '<div class="article-badges-container">';
        foreach ($badges as $badge) {
            $html .= self::renderBadgeElement($badge);
        }
        $html .= '</div>';

        return $html;
    }

    /**
     * Render the copyright section
     *
     * Supports both new format (object with content/code keys) and
     * legacy format (array of preset IDs) for backward compatibility.
     */
    public static function renderCopyright($copyrightPresetsJson, $selectedJson)
    {
        $presets = json_decode($copyrightPresetsJson, true);
        $selected = json_decode($selectedJson, true);

        if (empty($presets) || empty($selected)) {
            return '';
        }

        $isNewFormat = is_array($selected) && (isset($selected['content']) || isset($selected['code']));

        if ($isNewFormat) {
            return self::renderCopyrightNew($presets, $selected);
        } else {
            return self::renderCopyrightLegacy($presets, $selected);
        }
    }

    /**
     * Render copyright with new format
     */
    private static function renderCopyrightNew($presets, $selected)
    {
        $contentGroups = isset($presets['contentGroups']) ? $presets['contentGroups'] : [];
        $codePresets = isset($presets['codePresets']) ? $presets['codePresets'] : [];

        $contentSelection = isset($selected['content']) ? $selected['content'] : null;
        $codeSelection = isset($selected['code']) ? $selected['code'] : null;

        if (empty($contentSelection) && empty($codeSelection)) {
            return '';
        }

        $html = '<div class="copyright-notice-container">';
        $html .= '<div class="copyright-information-section">';
        $html .= '<div class="copyright-title-text">© 版权声明</div>';
        $html .= '</div>';
        $html .= '<div class="license-and-badges-section">';

        // Render content license
        if (!empty($contentSelection) && isset($contentSelection['type'])) {
            $contentType = $contentSelection['type'];
            $selectedMarks = isset($contentSelection['marks']) ? $contentSelection['marks'] : [];

            // Find group definition
            $groupDef = null;
            foreach ($contentGroups as $g) {
                if ($g['id'] === $contentType) {
                    $groupDef = $g;
                    break;
                }
            }

            if ($groupDef) {
                $html .= '<div class="license-row">';
                $html .= '<span class="license-declaration-text">本文采用</span>';
                $html .= '<div class="license-badges-container">';

                if (!empty($groupDef['hasMarks'])) {
                    // Group has custom marks (e.g., CC 4.0)
                    $groupMarks = isset($groupDef['marks']) ? $groupDef['marks'] : [];
                    $link = ($contentType === 'cc') ? self::buildCcLink($selectedMarks) : (isset($groupDef['link']) ? $groupDef['link'] : '');

                    // CC Main badge if type is cc
                    if ($contentType === 'cc') {
                        $ccTooltipAttr = ' data-tooltip="' . self::esc('知识共享 (Creative Commons)') . '"';
                        if (!empty($link)) {
                            $html .= '<a class="license-badge-item" href="' . self::esc($link) . '" target="_blank" rel="noopener noreferrer"' . $ccTooltipAttr . '>CC</a>';
                        } else {
                            $html .= '<div class="license-badge-item"' . $ccTooltipAttr . '>CC</div>';
                        }
                    }

                    // Render selected marks
                    foreach ($groupMarks as $mDef) {
                        $mId = isset($mDef['id']) ? $mDef['id'] : (isset($mDef['text']) ? $mDef['text'] : '');
                        if (in_array($mId, $selectedMarks)) {
                            $text = isset($mDef['text']) ? $mDef['text'] : $mId;
                            $tooltip = isset($mDef['tooltip']) ? $mDef['tooltip'] : '';
                            $tooltipAttr = !empty($tooltip) ? ' data-tooltip="' . self::esc($tooltip) . '"' : '';

                            if (!empty($link)) {
                                $html .= '<a class="license-badge-item" href="' . self::esc($link) . '" target="_blank" rel="noopener noreferrer"' . $tooltipAttr . '>' . self::esc($text) . '</a>';
                            } else {
                                $html .= '<div class="license-badge-item"' . $tooltipAttr . '>' . self::esc($text) . '</div>';
                            }
                        }
                    }
                } else {
                    // Single badge group (e.g. CC0, All Rights Reserved, or user custom single groups)
                    $badge = isset($groupDef['badge']) ? $groupDef['badge'] : null;
                    $badgeText = $badge ? $badge['text'] : $groupDef['name'];
                    $badgeTooltip = ($badge && !empty($badge['tooltip'])) ? $badge['tooltip'] : (isset($groupDef['description']) ? $groupDef['description'] : '');
                    $tooltipAttr = !empty($badgeTooltip) ? ' data-tooltip="' . self::esc($badgeTooltip) . '"' : '';
                    $link = isset($groupDef['link']) ? $groupDef['link'] : '';

                    if (!empty($link)) {
                        $html .= '<a class="license-badge-item" href="' . self::esc($link) . '" target="_blank" rel="noopener noreferrer"' . $tooltipAttr . '>' . self::esc($badgeText) . '</a>';
                    } else {
                        $html .= '<div class="license-badge-item"' . $tooltipAttr . '>' . self::esc($badgeText) . '</div>';
                    }
                }

                $html .= '</div>';
                $html .= '<span class="license-declaration-text">协议发布，请遵守相关规定。</span>';
                $html .= '</div>';
            }
        }

        // Render code license
        if (!empty($codeSelection)) {
            $codeDef = null;
            foreach ($codePresets as $cp) {
                if ($cp['id'] === $codeSelection) {
                    $codeDef = $cp;
                    break;
                }
            }

            if ($codeDef) {
                $html .= '<div class="license-row">';
                $html .= '<span class="license-declaration-text">本文中包含的代码采用</span>';

                $badgeLabel = isset($codeDef['badgeLabel']) ? $codeDef['badgeLabel'] : 'OPEN SOURCED';
                $badgeValue = isset($codeDef['badgeValue']) ? $codeDef['badgeValue'] : $codeDef['name'];
                $badgeColor = isset($codeDef['badgeColor']) ? $codeDef['badgeColor'] : '#555555';
                $tooltip = !empty($codeDef['description']) ? $codeDef['description'] : '';
                $tooltipAttr = !empty($tooltip) ? ' data-tooltip="' . self::esc($tooltip) . '"' : '';

                if (!empty($codeDef['link'])) {
                    $html .= '<a class="badge-group" href="' . self::esc($codeDef['link']) . '" target="_blank" rel="noopener noreferrer"' . $tooltipAttr . '>';
                } else {
                    $html .= '<div class="badge-group"' . $tooltipAttr . '>';
                }

                $html .= '<span class="badge-label">' . self::esc($badgeLabel) . '</span>';
                $html .= '<span class="badge-value" style="background-color:' . self::esc($badgeColor) . ';">' . self::esc($badgeValue) . '</span>';

                if (!empty($codeDef['link'])) {
                    $html .= '</a>';
                } else {
                    $html .= '</div>';
                }

                $html .= '<span class="license-declaration-text">协议开源。</span>';
                $html .= '</div>';
            }
        }

        $html .= '</div>';
        $html .= '</div>';

        return $html;
    }

    /**
     * Render copyright with legacy format (backward compatibility)
     */
    private static function renderCopyrightLegacy($presets, $selectedIds)
    {
        if (isset($presets['contentGroups']) || isset($presets['codePresets'])) {
            return '';
        }

        if (!is_array($selectedIds))
            return '';

        $contentLicenses = [];
        $codeLicenses = [];

        foreach ($presets as $preset) {
            if (in_array($preset['id'], $selectedIds)) {
                $type = isset($preset['type']) ? $preset['type'] : 'content';
                if ($type === 'code') {
                    $codeLicenses[] = $preset;
                } else {
                    $contentLicenses[] = $preset;
                }
            }
        }

        if (empty($contentLicenses) && empty($codeLicenses)) {
            return '';
        }

        $html = '<div class="copyright-notice-container">';
        $html .= '<div class="copyright-information-section">';
        $html .= '<div class="copyright-title-text">© 版权声明</div>';
        $html .= '</div>';
        $html .= '<div class="license-and-badges-section">';

        // Render content licenses
        foreach ($contentLicenses as $license) {
            $html .= '<div class="license-row">';
            $html .= '<span class="license-declaration-text">本文采用</span>';
            $html .= '<div class="license-badges-container">';

            if (!empty($license['badges'])) {
                foreach ($license['badges'] as $badge) {
                    $tooltip = !empty($badge['tooltip']) ? ' data-tooltip="' . self::esc($badge['tooltip']) . '"' : '';
                    if (!empty($license['link'])) {
                        $html .= '<a class="license-badge-item" href="' . self::esc($license['link']) . '" target="_blank" rel="noopener noreferrer"' . $tooltip . '>';
                        $html .= self::esc($badge['text']);
                        $html .= '</a>';
                    } else {
                        $html .= '<div class="license-badge-item"' . $tooltip . '>';
                        $html .= self::esc($badge['text']);
                        $html .= '</div>';
                    }
                }
            }

            $html .= '</div>';
            $html .= '<span class="license-declaration-text">协议发布，请严格遵守协议规定。</span>';
            $html .= '</div>';
        }

        // Render code licenses
        if (!empty($codeLicenses)) {
            $html .= '<div class="license-row">';
            $html .= '<span class="license-declaration-text">本文中包含的代码采用</span>';

            foreach ($codeLicenses as $license) {
                $badgeLabel = isset($license['badgeLabel']) ? $license['badgeLabel'] : 'OPEN SOURCED';
                $badgeValue = isset($license['badgeValue']) ? $license['badgeValue'] : $license['name'];
                $badgeColor = isset($license['badgeColor']) ? $license['badgeColor'] : '#555555';
                $tooltip = !empty($license['description']) ? $license['description'] : '';
                $tooltipAttr = !empty($tooltip) ? ' data-tooltip="' . self::esc($tooltip) . '"' : '';

                if (!empty($license['link'])) {
                    $html .= '<a class="badge-group" href="' . self::esc($license['link']) . '" target="_blank" rel="noopener noreferrer"' . $tooltipAttr . '>';
                } else {
                    $html .= '<div class="badge-group"' . $tooltipAttr . '>';
                }

                $html .= '<span class="badge-label">' . self::esc($badgeLabel) . '</span>';
                $html .= '<span class="badge-value" style="background-color:' . self::esc($badgeColor) . ';">' . self::esc($badgeValue) . '</span>';

                if (!empty($license['link'])) {
                    $html .= '</a>';
                } else {
                    $html .= '</div>';
                }
            }

            $html .= '<span class="license-declaration-text">协议开源。</span>';
            $html .= '</div>';
        }

        $html .= '</div>';
        $html .= '</div>';

        return $html;
    }

    /**
     * Build the full article footer HTML
     */
    public static function render($widget, $options)
    {
        $badgesEnabled = is_null($options->Dear_badgesEnabled) ? true : (bool) $options->Dear_badgesEnabled;
        $copyrightEnabled = is_null($options->Dear_copyrightEnabled) ? true : (bool) $options->Dear_copyrightEnabled;

        $showBadges = $widget->fields->showBadges;
        $showCopyright = $widget->fields->showCopyright;

        if ($showBadges === '0') {
            $badgesEnabled = false;
        } elseif ($showBadges === '1') {
            $badgesEnabled = true;
        }

        if ($showCopyright === '0') {
            $copyrightEnabled = false;
        } elseif ($showCopyright === '1') {
            $copyrightEnabled = true;
        }

        if (!$badgesEnabled && !$copyrightEnabled) {
            return '';
        }

        $badgeGroupsJson = is_null($options->Dear_badgeGroups) ? self::defaultBadgeGroups() : $options->Dear_badgeGroups;
        $copyrightPresetsJson = is_null($options->Dear_copyrightPresets) ? self::defaultCopyrightPresets() : $options->Dear_copyrightPresets;

        $defaultBadgesJson = is_null($options->Dear_badgesDefault) ? '[]' : $options->Dear_badgesDefault;
        $defaultCopyrightJson = is_null($options->Dear_copyrightDefault) ? '{}' : $options->Dear_copyrightDefault;

        $articleBadgesRaw = $widget->fields->articleBadges;
        $articleCopyrightRaw = $widget->fields->articleCopyright;

        $articleBadgesJson = !empty($articleBadgesRaw) ? $articleBadgesRaw : $defaultBadgesJson;
        $articleCopyrightJson = !empty($articleCopyrightRaw) ? $articleCopyrightRaw : $defaultCopyrightJson;

        $badgesHtml = $badgesEnabled ? self::renderBadges($badgeGroupsJson, $articleBadgesJson) : '';
        $copyrightHtml = $copyrightEnabled ? self::renderCopyright($copyrightPresetsJson, $articleCopyrightJson) : '';

        if (empty($badgesHtml) && empty($copyrightHtml)) {
            return '';
        }

        $html = '<div class="article-footer-wrapper">';
        $html .= $badgesHtml;
        $html .= $copyrightHtml;
        $html .= '</div>';

        return $html;
    }
}
